"""Builds assets/js/data/stahl.js — a condensed, structured prescribing dataset
derived from Stahl's Essential Psychopharmacology: Prescriber's Guide (7th ed.).

Usage: python3 tools/build_stahl.py <dir containing stahl.json and ind.json>
(stahl.json / ind.json are produced from the PDF with pdftotext / pdftohtml; see README).
Only short factual prescribing fields are kept; narrative prose ("Pearls",
"How the drug works", etc.) is intentionally excluded.
"""
import json, re, sys
src = sys.argv[1]
book = json.load(open(src + '/stahl.json', encoding='utf8'))
ind = json.load(open(src + '/ind.json', encoding='utf8'))
IDS = {
 'fluoxetine':'Fluoxetine','sertraline':'Sertraline','escitalopram':'Escitalopram','citalopram':'Citalopram','paroxetine':'Paroxetine','fluvoxamine':'Fluvoxamine',
 'venlafaxine':'Venlafaxine','desvenlafaxine':'Desvenlafaxine','duloxetine':'Duloxetine','levomilnacipran':'Levomilnacipran',
 'amitriptyline':'Amitriptyline','nortriptyline':'Nortriptyline','imipramine':'Imipramine','clomipramine':'Clomipramine','desipramine':'Desipramine',
 'phenelzine':'Phenelzine','tranylcypromine':'Tranylcypromine','isocarboxazid':'Isocarboxazid','selegiline':'Selegiline',
 'mirtazapine':'Mirtazapine','bupropion':'Bupropion','trazodone':'Trazodone','vortioxetine':'Vortioxetine','vilazodone':'Vilazodone','agomelatine':'Agomelatine',
 'esketamine':'Esketamine','ketamine':'Ketamine',
 'clozapine':'Clozapine','olanzapine':'Olanzapine','quetiapine':'Quetiapine','risperidone':'Risperidone','paliperidone':'Paliperidone','aripiprazole':'Aripiprazole',
 'brexpiprazole':'Brexpiprazole','cariprazine':'Cariprazine','ziprasidone':'Ziprasidone','lurasidone':'Lurasidone','asenapine':'Asenapine','lumateperone':'Lumateperone',
 'haloperidol':'Haloperidol','chlorpromazine':'Chlorpromazine','pimavanserin':'Pimavanserin',
 'lithium':'Lithium','valproate':'Valproate','carbamazepine':'Carbamazepine','lamotrigine':'Lamotrigine','oxcarbazepine':'Oxcarbazepine',
 'lorazepam':'Lorazepam','diazepam':'Diazepam','clonazepam':'Clonazepam','alprazolam':'Alprazolam','midazolam':'Midazolam',
 'buspirone':'Buspirone','hydroxyzine':'Hydroxyzine','pregabalin':'Pregabalin','gabapentin':'Gabapentin','propranolol':'Propranolol','prazosin':'Prazosin',
 'zolpidem':'Zolpidem','eszopiclone':'Eszopiclone','zaleplon':'Zaleplon','temazepam':'Temazepam','ramelteon':'Ramelteon','suvorexant':'Suvorexant','lemborexant':'Lemborexant','doxepin':'Doxepin',
 'methylphenidate':'Methylphenidate (D,L)','amphetamine':'Amphetamine (D,L)','lisdexamfetamine':'Lisdexamfetamine','atomoxetine':'Atomoxetine','guanfacine':'Guanfacine','clonidine':'Clonidine','modafinil':'Modafinil',
 'buprenorphine':'Buprenorphine','naltrexone':'Naltrexone','acamprosate':'Acamprosate','disulfiram':'Disulfiram','varenicline':'Varenicline','lofexidine':'Lofexidine',
 'donepezil':'Donepezil','rivastigmine':'Rivastigmine','galantamine':'Galantamine','memantine':'Memantine',
 'valbenazine':'Valbenazine','deutetrabenazine':'Deutetrabenazine','benztropine':'Benztropine',
}
F = [('cls','Class',3),('dose','Usual Dosage Range',4),('forms','Dosage Forms',6),('howToDose','How to Dose',6),('tips','Dosing Tips',5),
     ('pk','Pharmacokinetics',6),('interactions','Drug Interactions',7),('doNotUse','Do Not Use',6),('warnings','Other Warnings/Precautions',6),
     ('renal','Renal Impairment',3),('hepatic','Hepatic Impairment',3),('cardiac','Cardiac Impairment',3),('elderly','Elderly',3),
     ('children','Children and Adolescents',4),('pregnancy','Pregnancy',4),('breast','Breast Feeding',2),('howToStop','How to Stop',4),
     ('habit','Habit Forming',2),('overdose','Overdose',2),('longTerm','Long-Term Use',2),('tests','Tests',5),
     ('lifeThreat','Life-Threatening or Dangerous Side Effects',6),('notable','Notable Side Effects',6),('weight','Weight Gain',1),('sedation','Sedation',1),
     ('onset','How Long Until It Works',2),('reading','Suggested Reading',8)]
DROP = re.compile(r'^(Effective June 30, 2015|National Pregnancy Registry|Carefully weigh the risks and benefits|\(bold for FDA)')
def clean(s):
    s = s.replace('✽', '').replace(' ,', ',').replace(' .', '.').replace(' :', ':').replace(' ;', ';')
    s = re.sub(r'\s+', ' ', s).strip()
    return s if len(s) <= 420 else s[:417].rsplit(' ', 1)[0] + '…'
out = {}
for k, name in IDS.items():
    ch = book[name]; rec = {'title': name}
    for key, head, cap in F:
        items = [clean(x) for x in ch.get(head, []) if not DROP.match(x.strip())]
        items = [x for x in items if x]
        if key in ('weight', 'sedation'):
            items = [x for x in items if re.match(r'(Reported|Many|Occurs|Frequent|Problematic|None|Some|May|Sedation|Tolerance|Transdermal)', x)]
        if items: rec[key] = items[:cap]
    rec['indications'] = [{'t': clean(i['t']), 'fda': i['fda']} for i in ind.get(name, [])]
    out[k] = rec
js = ('/* AUTO-GENERATED by tools/build_stahl.py — condensed prescribing reference from\n'
      ' * Stahl SM. Stahl\'s Essential Psychopharmacology: Prescriber\'s Guide, 7th ed. Cambridge University Press, 2021.\n'
      ' * Do not edit by hand; re-run the build script. Bold (FDA-approved) flags are taken from the book\'s typography. */\n'
      'window.PA = window.PA || {};\nPA.stahl = ' + json.dumps(out, ensure_ascii=False, separators=(',', ':')) + ';\n')
open('assets/js/data/stahl.js', 'w', encoding='utf8').write(js)
print(len(out), 'drugs;', len(js)//1024, 'KB')
